/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3dd",
        "primary-fixed": "#aef2bb",
        "on-tertiary-fixed-variant": "#544600",
        "inverse-on-surface": "#eff2eb",
        "secondary-fixed": "#ffe088",
        "on-surface": "#191d19",
        "secondary-container": "#fed65b",
        "tertiary": "#705d00",
        "on-primary-container": "#79bb87",
        "surface-container": "#ecefe8",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#2a6a3f",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3dd",
        "tertiary-fixed": "#ffe16d",
        "surface-dim": "#d8dbd5",
        "surface-container-low": "#f2f4ee",
        "inverse-surface": "#2e312d",
        "inverse-primary": "#93d6a0",
        "on-primary-fixed-variant": "#0b5229",
        "secondary": "#735c00",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#e9c349",
        "on-error-container": "#93000a",
        "background": "#f8faf4",
        "tertiary-fixed-dim": "#e9c400",
        "outline-variant": "#c0c9be",
        "surface-container-high": "#e6e9e3",
        "on-tertiary-container": "#4b3e00",
        "primary-fixed-dim": "#93d6a0",
        "primary-container": "#004b23",
        "on-background": "#191d19",
        "error-container": "#ffdad6",
        "tertiary-container": "#c8a900",
        "on-secondary": "#ffffff",
        "outline": "#707970",
        "on-surface-variant": "#404941",
        "on-secondary-fixed": "#241a00",
        "primary": "#003215",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-fixed": "#221b00",
        "on-secondary-container": "#745c00",
        "on-tertiary": "#ffffff",
        "surface": "#f8faf4",
        "on-primary-fixed": "#00210c",
        "surface-bright": "#f8faf4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "arthaku-headline": ["Manrope", "sans-serif"],
        "arthaku-body": ["Inter", "sans-serif"],
        "arthaku-label": ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
